services:
  - type: web
    name: otmivdeneg
    runtime: node
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TWITCH_CLIENT_SECRET
        sync: false
